Eval plugin: mark exceptions
haskell/haskell-language-server pull request #2775
Opened 2022-03-12 19:01 UTC by xsebek

This change will format exception results in the same way as doctest:
```haskell
>>> if error "-1" then 1 else 0
------------------
-- current:
-1
------------------
-- new:
*** Exception: -1
```

TODO:
- [ ] fix (pseudo)doctest examples in code

- Fixes #2353

2022-03-12 21:16 UTC, xsebek commented
Hi @jneira, there seems to be no code owner of the eval plugin - do you know who might be familiar with the code? :slightly_smiling_face:

2022-03-12 21:24 UTC, pepeiborra approved these changes
Looks good to me.

2022-03-12 21:35 UTC, Ailrun requested changes
This no "Exception" message is intended AFAIK: https://github.com/haskell/haskell-language-server/tree/master/plugins/hls-eval-plugin#multiline-output

I think we cannot change this at least before we have somewhat "proper" handling of IO.

2022-03-12 21:45 UTC, Ailrun commented
C.C. @tittoassini

2022-03-12 21:54 UTC, xsebek commented
> This no "Exception" message is intended AFAIK: https://github.com/haskell/haskell-language-server/tree/master/plugins/hls-eval-plugin#multiline-output

Thanks, @Ailrun, I was not aware of this hack. I do find the missing message a bit confusing, but if someone is using `error` to emulate `putStr` then I can let this rest for a while.

2022-03-13 09:15 UTC, pepeiborra commented
I was not aware of this hack either! We should strive to make this hack unnecessary, some options come to mind: 

* Capturing output can be solved by using the external interpreter (`-fexternal-interpreter`). We should revisit using it for the eval plugin, but this might be challenging or even impossible.
* We could wrap all the user code in a custom exception type with a crafted Show instance that doesn't escape output. Then we catch all other exception types and add the "*** Exception" markup.

What do you think @Ailrun ?

2022-03-13 15:21 UTC, Ailrun commented
@pepeiborra I think the second would be more feasible. If we can handle IO better, that would be better, but that may take quite effort

2022-03-17 16:24 UTC, xsebek commented
Hi @pepeiborra, I am not entirely sure what you mean by the second option?

I imagine this could be hacked around by recognizing some prefix like `"PRETEND_I_AM_IO: "`.

If supporting this hack should involve more effort, I would rather attempt to fix the IO instead :slightly_smiling_face:

2022-03-17 16:51 UTC, pepeiborra commented
Sorry I wasn't clear: The only way to properly fix #1977 is by using the external interpreter, which is far from obvious.

2022-03-17 18:31 UTC, xsebek commented
Yes, I understood that the first option is fixing #1977 with an external interpreter though I have no idea how to do that (yet).

What I can not imagine is how to "wrap all the user code" which you suggested as the second option. :thinking:

2022-03-19 12:27 UTC, pepeiborra commented
Yes, I can see now that the 2nd option is not trivial either.

2022-03-19 14:42 UTC, xsebek commented
Another solution that comes to mind would be to make this configurable by the user.

Currently, the eval plugin has the `#diff` property for WAS/NOW (which is passed to `runTests` so it's almost there).

So I suggest adding an `#exception` property (`False` by default) with the hint:

> Enable marking exceptions with `*** Exception:` similarly to doctest and GHCi.

What do you think, @pepeiborra, @Ailrun? It seems relatively low effort and once we get better IO support, we could just turn it on by default or keep it off.  :slightly_smiling_face:

2022-03-19 19:16 UTC, xsebek commented
OK, the behaviour is now configurable via `haskell.plugin.eval.config.exception` (default `false`) and there is one more test for this configuration option.

Does this resolve your concerns @Ailrun? Btw. thanks for the scaffolding around `diff`. :slightly_smiling_face:

2022-03-19 23:03 UTC, Ailrun approved these changes
LGTM :) Here is one minor comment for documentation.

2022-03-19 23:03 UTC, Ailrun commented on plugins/hls-eval-plugin/README.md
> +This assumes you did not turn on exception marking (see #)
It looks like a link is missing?

2022-03-19 23:50 UTC, xsebek commented on plugins/hls-eval-plugin/README.md
> +This assumes you did not turn on exception marking (see #)
Thanks, I was about to look up how to link sections and got distracted. :sweat_smile: 

Fixed :heavy_check_mark:

2022-03-20 00:19 UTC, xsebek commented
At the last minute, I remembered to check the docs for configuration options and added the eval section. :sweat_smile: 

I wonder if it needs to be added to vscode-haskell too?

2022-03-20 17:32 UTC, michaelpj approved these changes
Docs look fine to me. The way the config options are documented is suboptimal, but this doesn't make it worse!

I don't know what the deal is with exposing options in `vscode-haskell`...

2022-03-20 19:35 UTC, merged