Implement sharing for hls-graph Keys
haskell/haskell-language-server pull request #3206
Opened 2022-09-21 05:01 UTC by wz1000

On large projects, duplicate Keys start to comprise a significant (~5-10%) fraction of the heap.
This becomes better if we use `Int`s as keys and de-duplicate the actual values by storing them
in maps. `Key`s are mostly just compared and hash during usual operation, printing them out is
rare so a lookup shouldn't pessimize it much.

Also use HashSets to keep track of dependencies.
However, this means that the underlying value for `Key`s will never be garbage collected once allocated.

2022-09-21 16:24 UTC, wz1000 commented on hls-graph/src/Development/IDE/Graph/Internal/Types.hs
> +    hashWithSalt i (KeyValue x) = hashWithSalt i (typeOf x, x)
How can you hash the key, which is derived from the order of insertions into the map, from the `KeyValue`?

2022-09-21 16:46 UTC, pepeiborra commented on hls-graph/src/Development/IDE/Graph/Internal/Types.hs
> +    hashWithSalt i (KeyValue x) = hashWithSalt i (typeOf x, x)
Can't you store the `Key` itself in the `KeyValue`?

2022-09-21 16:52 UTC, wz1000 commented on hls-graph/src/Development/IDE/Graph/Internal/Types.hs
> +    hashWithSalt i (KeyValue x) = hashWithSalt i (typeOf x, x)
But you need the `KeyValue` first to check in the map for duplicates.

2022-09-21 16:58 UTC, pepeiborra commented on hls-graph/src/Development/IDE/Graph/Internal/Types.hs
> +    hashWithSalt i (KeyValue x) = hashWithSalt i (typeOf x, x)
Right

2022-09-21 17:02 UTC, pepeiborra approved these changes
Approved. Please share some benchmarks showing the memory savings when you have a chance!

2022-09-23 07:04 UTC, pepeiborra requested changes
Can we drop the `Int` proxy (`Key`) and the `IntMap`? 
`newKey` will lookup in the `KeyMap` and return the existing value if any, recovering sharing. 

What's the benefit of keeping an extra mapping?

2022-09-27 06:45 UTC, wz1000 commented
> Can we drop the `Int` proxy (`Key`) and the `IntMap`? `newKey` will lookup in the `KeyMap` and return the existing value if any, recovering sharing.
> 
> What's the benefit of keeping an extra mapping?

I tried this first, but GHC unpacks the Key and we lose sharing at that point.

2022-09-27 09:12 UTC, pepeiborra commented
> I tried this first, but GHC unpacks the Key and we lose sharing at that point.

Worth adding a comment about this, I believe my previous attempt to share keys must have failed for this reason

2022-09-27 09:15 UTC, michaelpj commented
> I tried this first, but GHC unpacks the Key and we lose sharing at that point.

Maybe it's a bit too sensitive, but can we do something to prevent GHC from unpacking the key? e.g. not import the constructor in the module in question?

2022-09-28 09:52 UTC, wz1000 commented on hls-graph/src/Development/IDE/Graph/Internal/Types.hs
> +  hashWithSalt i (UnsafeMkKey x) = hashWithSalt i x
I think it makes it clearer to write these explicitly, given that we have some weird stuff going on with the Key pattern synonym.

2022-09-28 11:13 UTC, wz1000 commented on hls-graph/src/Development/IDE/Graph/Internal/Types.hs
> +data ResultDeps = UnknownDeps | AlwaysRerunDeps !(HashSet Key) | ResultDeps !(HashSet Key)
I've introduced `KeyMap` and `KeySet` backed by `IntMap` and `IntSet`.

2022-09-28 11:14 UTC, wz1000 commented
> Maybe it's a bit too sensitive, but can we do something to prevent GHC from unpacking the key? e.g. not import the constructor in the module in question?

I don't think this is possible currently. Would be a good feature request though.

2022-09-28 12:10 UTC, wz1000 commented
I've also added sharing of the rendered `Key` as `Text` to avoid duplicating the rendered Key in the diagnostic store, else we get a duplicate of each key as a rendered `Text` value for each file in the project.

2022-10-08 16:35 UTC, pepeiborra approved these changes
Can we have those benchmark results?

2022-10-24 07:45 UTC, wz1000 commented
Here are some profiles from before and after

before (heap size): 
![2022-10-21-211021_grab](https://user-images.githubusercontent.com/4812498/197473347-9dc7657a-4892-453e-bf68-3cf845f4ee8d.png)

before (keys in heap): 
![2022-10-21-211050_grab](https://user-images.githubusercontent.com/4812498/197473410-4b4a87c2-fa12-49a1-98eb-2f92d12a3b4d.png)

In the second image you can see that just the top allocation site of duplicate keys is responsible for ~200MB of live bytes. These are all eliminated by this patch.

after (heap size): 
![2022-09-27-140932_grab](https://user-images.githubusercontent.com/4812498/197473724-6f80a12a-8966-4179-8217-baf1f7444e1e.png)

2022-10-24 09:20 UTC, merged