Bump ghcide submodule
haskell/haskell-language-server pull request #395
Opened 2020-09-12 10:26 UTC by pepeiborra

To pick up the relative import path fix

2020-09-12 10:30 UTC, wz1000 approved these changes

2020-09-12 14:59 UTC, Ailrun commented
Hm...formatter test repeats a part of code for unknown reason... :(

2020-09-12 19:00 UTC, wz1000 requested changes
There is a rebase error here: https://github.com/haskell/ghcide/compare/master...hls-3.2#diff-b3c76360204f553be39aaf5ae07b8d67R601

We want to generate the hie file even if errors are deferred, or we won't get hovers/definitions/etc. when there are any defered errors.

I've cleaned up the code in https://github.com/haskell/ghcide/pull/784, so https://github.com/haskell/haskell-language-server/pull/396 supersedes this

2020-09-13 08:20 UTC, pepeiborra commented
Closing in favour of #396

2020-09-13 08:20 UTC, closed without merging