POC: merge plugins into the HLS package
haskell/haskell-language-server pull request #3976
Opened 2024-01-17 17:28 UTC by michaelpj

This is a POC for merging all the plugin packages into the HLS package, as discussed in https://github.com/haskell/haskell-language-server/issues/3556.

I just did the first two plugins alphabetically to show what it looks like, it's pretty mechanical.

To reiterate, the advantages are:
- Fewer packages to upload
- Less repeated metadata
- Fewer versions
- Ability to use common stanzas to e.g. have the same set of warnings everywhere (I would do this as a follow up if we decide to go this route)

Things seem to still work fine. The main annoyances are:
- Can't `cd` into a plugin directory and `cabal build`/`cabal test`
- Can't `cabal test <plugin-name>`, instead need `cabal test <plugin-name>-tests`

I think overall it's still going to be a pretty big improvement

2024-01-17 19:46 UTC, soulomoon commented
One high draw back, it prevent us from working on a single plugin along.

2024-01-17 19:50 UTC, michaelpj commented
I don't think it does? You can still just build the component for the plugin and it won't build anything else.

2024-01-17 20:49 UTC, soulomoon commented
But we can no longer open an single editor containing just one plugin dir and get hls support 🤔

2024-01-17 21:00 UTC, michaelpj commented
I don't see why not? We do support single components of packages just fine? And it'll be better as the multi-component stuff rolls out (but that's already bad if you try to edit multiple packages today)

2024-01-17 22:05 UTC, soulomoon commented
> I don't see why not? We do support single components of packages just fine? And it'll be better as the multi-component stuff rolls out (but that's already bad if you try to edit multiple packages today)

Thanx for clearing out my concern on this.

2024-01-18 09:17 UTC, michaelpj commented
Another downside: stack supports building packages with internal libraries (the CI run succeeded!), but it doesn't do per-component builds, so the dev experience using stack will probably suck. I'm not sure how much we care about that these days :shrug:

2024-01-24 22:14 UTC, michaelpj commented
No longer a POC! 

There is still plenty to do here with cleaning up the now rather monolithic cabal file, making better use of common stanzas etc, but I'm keen to land this before too long since it's very conflict-y.

2024-01-24 22:17 UTC, michaelpj commented
cc @fendor @wz1000  as discussed

2024-01-24 22:22 UTC, michaelpj commented
Follow up todos:
- Make all components which condition on `pedantic` use the common stanza for that
- Add a common stanza for `default-language`
- Maybe merge in some more packages. I think only `hls-test-utils`, everything else is a dependency of `ghcide` and so needs to stay out for now.
- Maybe try and organize the cabal file to be a bit more navigable

2024-01-25 04:55 UTC, jhrcek reviewed
I like this approach more than the previous.
Few nitpicks about ghc-options - warnings, but I will work on those anyway in followup PRs, so feel free to ignore.

2024-01-25 04:55 UTC, jhrcek commented on haskell-language-server.cabal
> +  ghc-options:        -Wno-unticked-promoted-constructors
Can be removed - is now in common warnings.

2024-01-25 04:55 UTC, jhrcek commented on haskell-language-server.cabal
> +  ghc-options:
You can import common warnings for this lib and remove this.

2024-01-25 05:10 UTC, jhrcek commented on haskell-language-server.cabal
> +  ghc-options:      -O0 -threaded -rtsopts -with-rtsopts=-N -Wunused-imports
I'm pretty sure that -Wunused-imports are enabled by -Wall, so you could remove it from here since you're importing -Wall via `import: warnings`

2024-01-25 09:22 UTC, michaelpj commented
Yeah, I didn't do any cleanup on the cabal file contents, just moved them over as-is. Cleanups later!

2024-01-25 12:04 UTC, michaelpj commented
Hmmm... is that a long-path error?

2024-01-25 12:08 UTC, michaelpj commented
Yup, the path is 261 characters. I'm going to shorten the component name. Generally I think we could now strip the `hls-` prefixes from everything at least. Frankly, maybe also the `-plugin` suffix?

2024-01-25 14:49 UTC, michaelpj commented
Still can't get everything below the limit. At this point it's either do something ad-hoc or turn off GHC9.2+windows

2024-01-26 10:56 UTC, fendor commented
> Generally I think we could now strip the hls- prefixes from everything at least. Frankly, maybe also the -plugin suffix?

Changing `hls-fourmolu-plugin` to `fourmolu` will cause a fair amount of confusion. Almost all plugins that essentially wrap a tool would be weird that way.

2024-01-26 10:58 UTC, michaelpj commented
Yeah, I think we should probably keep `-plugin`.

2024-01-26 11:02 UTC, fendor commented
Personally, I like the explicitness :shrug: It signals an HLS namespace

2024-01-26 11:14 UTC, michaelpj commented
Right, but once it's a component of the `haskell-language-server` package it's already namespaced. The full name will be `haskell-language-server:hls-ormolu-plugin` which seems redundant to me.

2024-01-26 11:15 UTC, michaelpj commented
You definitely want it when it's _not_ a subcomponent.

2024-01-26 15:03 UTC, michaelpj commented
Okay, I think this is now all working, just getting through CI nondeterminism. I've reverted all component name changes for now since I've sidestepped the long path issue. We can discuss that later.

Anyone want to approve?

2024-01-27 16:05 UTC, joyfulmantis approved these changes
LGTM

2024-01-27 16:52 UTC, fendor requested changes
I think the tests are not run in CI 
![image](https://github.com/haskell/haskell-language-server/assets/8463814/baee7c00-6f80-4525-8def-ba8b9b100f1e)

2024-01-27 19:33 UTC, georgefst commented
I suppose the `fourmolu`/`fourmolu-plugin`/`hls-fourmolu-plugin` trade-off comes down to whether sublibraries can only over be referred to outside the package in qualified form. I've dabbled a little with multiple-public-libraries support, but I don't know this off the top of my head, though I'd assume they can't.

In general, this change seems a sensible one. I had assumed when the project started back in 2020 that we'd eventually move towards plugins being maintained outside of the HLS organisation entirely, but this doesn't really work without them being genuinely runtime-pluginnable. And as far as I understand it, this would require significant improvements in GHC dynamic linking support, which no one wants to work on...

tl;dr All good.

2024-01-28 00:50 UTC, joyfulmantis commented
> I think the tests are not run in CI ![image](https://private-user-images.githubusercontent.com/8463814/300192214-baee7c00-6f80-4525-8def-ba8b9b100f1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MDMyOTEsIm5iZiI6MTcwNjQwMjk5MSwicGF0aCI6Ii84NDYzODE0LzMwMDE5MjIxNC1iYWVlN2MwMC02ZjgwLTQ1MjUtOGRlZi1iYThiOWIxMDBmMWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMDA0OTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjRlZDhlZWMwZWZhMGM4MzU1NjhmYWJiZTgwNGVmMThkZmY5ZTBmYTMxY2VkZDYwMzFhYzRiZmNhYTUxMzlmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LQM2EEEBwt_eStehQ95tV2mUiU8mIbzIzesF00ZxKtA)

Yikes! yes we definitely want those tests still

2024-01-28 18:11 UTC, michaelpj commented
> I think the tests are not run in CI

What on earth... that is so odd. It works fine for me locally. Investigating

2024-01-28 18:18 UTC, michaelpj commented
> I suppose the fourmolu/fourmolu-plugin/hls-fourmolu-plugin trade-off comes down to whether sublibraries can only over be referred to outside the package in qualified form

Note that these are not currently _public_ sublibraries. We could make them public, but I don't know that there are any actual consumers of them. So at the moment we're only using the much older and better-supported non-public internal libraries.

> I had assumed when the project started back in 2020 that we'd eventually move towards plugins being maintained outside of the HLS organisation entirely, but this doesn't really work without them being genuinely runtime-pluginnable

Yes, I think the _reality_ of how plugins are used by HLS is that they are a very handy method of code organization and responsibility allocation, but that's about it. And I think that's fine! My position has always been that nobody actually wants to do runtime customization of their HLS installation, they want it to just work.

2024-01-28 18:19 UTC, michaelpj commented
My suspicion is that the test issue was due to tasty-rerun actually working. I've deleted the caches relating to that from this PR and rerun everything, let's see if it now runs the tests.

2024-01-28 18:21 UTC, georgefst commented
> Note that these are not currently _public_ sublibraries.

Oh, I just assumed. It is _in principle_ a regression to make all these libraries unusable externally. Though I suspect no one's using them.

2024-01-28 18:23 UTC, michaelpj commented
Yes, it's for sure a regression in theory. But personally I _highly_ doubt that anyone is using them. You'd have to be assembling your own custom HLS, and not want to do it using HLS's cabal flags for some reason.

2024-01-28 19:16 UTC, michaelpj commented
Nope?

2024-01-28 20:19 UTC, michaelpj commented
It was tasty-rerun, turning it off makes the tests run. I don't know whether it's doing something dodgy, but it seems to be orthogonal to this PR at least.

2024-01-29 09:15 UTC, merged

2024-03-29 13:02 UTC, smunix commented
@michaelpj - it looks like this change broke `nix` rpath setting for plugins internal libraries. It fails during the `install_phase` for finding references to the `/build/` directory. Have `2.7.0.0` been installed successfully with `nix` at all?

2024-03-29 18:17 UTC, michaelpj commented
That seems like a question for the Nix Haskell folks? It builds with cabal, so if it doesn't build with the Nix setup then that's a bug in the Nix setup, I think.