Add common stanza to completion data
haskell/haskell-language-server pull request #4286
Opened 2024-06-08 13:28 UTC by VeryMilkyJoe

This allows fields and values to be completed correctly inside common stanzas
Fixes #4285.

2024-06-08 15:13 UTC, fendor approved these changes

2024-06-08 15:13 UTC, fendor requested changes
LGTM, thanks for looking into this! There is no test for the completions in common sections, yet, could you perhaps add one?

2024-06-08 16:34 UTC, VeryMilkyJoe commented
> LGTM, thanks for looking into this! There is no test for the completions in common sections, yet, could you perhaps add one?

Will do, good catch!

2024-06-09 09:48 UTC, michaelpj approved these changes

2024-06-09 10:34 UTC, merged