replace expectNoMoreDiagnostics with waitForAction's, saving 1s
haskell/haskell-language-server pull request #4332
Opened 2024-06-21 16:31 UTC by komikat

`expectNoMoreDiagnostics 1` waits for 1 second to establish that no diagnostics have been created, it has been replaced with waitForTypecheck and waitForAction "gethieast" for Haskell and cabal files respectively, shaving off 1 second each time. I'm not sure if I should wait for some other action for cabal files.

2024-06-21 16:39 UTC, soulomoon commented
you may also need to consider the debouncer delay

2024-06-21 17:09 UTC, komikat commented
looking into it, thanks!

2024-07-10 15:26 UTC, fendor requested changes

2024-07-10 15:26 UTC, fendor commented on plugins/hls-cabal-plugin/test/Main.hs
> +                    _ <- waitForAction "gethieast" cabalDoc
I can imagine this works, cabal files don't run this action, right?

2024-10-02 12:14 UTC, closed without merging