Cabal go to module's definition
haskell/haskell-language-server pull request #4380
Opened 2024-08-14 14:19 UTC by VenInf

### Go to the module's definition

If you click go-to definition on the field under `exposed-module` or `other-module`
it will open the file where this module was defined.

Video with an example:

https://github.com/user-attachments/assets/c5cdcb9e-4d24-4d6b-a83a-de34d8dcedf6

### Implementation details

The go-to definition function compares the highlighted text with modules in the cabal file.
If there is a match, it takes the respective build target and tries to fetch their `hsSourceDirs` from the `PackageDescription`. (by looking at all `buildInfos` with matching names).

After finding them, it constructs a path using directory where the cabal file is located, the info from `hsSourceDirs` and a name of the module converted to a path.
If the file exists it returns the `Definition` with the acquired location.

### What isn't implemented
 - [x] No tests
 - [x] Current solution can't differentiate modules with same names.
 - [x] Current solution to choose if a definition can be provided isn't great, and is just a chain of `if`'s
 - [ ] The range in location is just zero, instead of highlighting the name of the module.

2024-08-16 12:05 UTC, fendor requested changes
LGTM, couple of nitpicks, then this should be good to go!

2024-08-16 12:05 UTC, fendor commented on plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal.hs
> +      lookupBuildTargetPackageDescription :: PackageDescription -> Maybe T.Text -> [BuildInfo]
Docs please :)

2024-08-16 12:05 UTC, fendor commented on plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal.hs
> +      toHaskellFile moduleName = foldl1 (</>) (map T.unpack $ T.splitOn "." moduleName) ++ ".hs"
Instead of letting `foldl1` fail, handle this potential error and provide a proper error message for the user!

2024-08-16 12:05 UTC, fendor commented on plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/CabalFields.hs
> +-- and the module name bounded to them. If a target is a main library gives
```suggestion
-- and the module name bound to them. If a target is a main library gives
```

2024-08-16 12:09 UTC, VenInf commented on plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal.hs
> +      isModuleName name (_,  moduleName) = name == moduleName
I thought that they are very application-specific, and almost don't do what they promise.
But maybe I will be able to rewrite them to something better, I will look into it.

2024-08-20 15:41 UTC, VenInf commented
Noteworthy change:
Split one large `gotoDefinition` function to multiple specific ones.
This will hurt the performance a little bit, but hopefully make the addition of other definitions easier.

2024-08-21 13:28 UTC, VeryMilkyJoe requested changes
Thank you, this looks great! I just have some small comments.

2024-08-21 16:32 UTC, VenInf commented on plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Definition.hs
> +        Nothing -> Nothing
Oh, that's neat, forgot that it's possible.

2024-08-22 14:10 UTC, fendor approved these changes
LGTM, thanks!

2024-08-22 14:12 UTC, merged